name: DLL Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build-dll:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build DLL
        run: cmake --build build --config Release

      - name: Find bigbase.dll
        run: dir /s /b build\Release\bigbase.dll

      - name: Upload bigbase.dll artifact
        uses: actions/upload-artifact@v4
        with:
          name: bigbase.dll
          path: build/Release/bigbase.dll
